# site properties and page defaults
title: OUNLP — Natural Language Processing Lab
subtitle: University of Oklahoma, School of Computer Science
description: Research on dialogue & discourse, structured prediction, large‑language‑model alignment and agentic systems, multimodal interaction, and trustworthy AI for education and healthcare.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: jie.cao@ou.edu
  orcid:
  google-scholar: McBrjX4AAAAJ
  github: https://github.com/ounlp
  twitter:
  youtube:

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
  - vendor
  - .bundle
  - Gemfile
  - Gemfile.lock
